
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Semih Durbal
 */
public class OyunKayitEkrani extends javax.swing.JFrame {


    private Connection con = null;

    private PreparedStatement preparedStatement = null;

    private Statement statement = null;



    public OyunKayitEkrani(){
        initComponents();
        String url = "jdbc:mysql://"+KullaniciKayitlari.host+":"+KullaniciKayitlari.port+"/"+KullaniciKayitlari.db_ismi+"?useUnicode = true&chracterEncoding = utf8";
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            System.out.println("Driver Bulunamadı.");
        }
        try {
            con = DriverManager.getConnection(url,KullaniciKayitlari.kullanici_adi,KullaniciKayitlari.parola);
            System.out.println("Bağlantı Başarılı");
        } catch (SQLException e) {
            System.out.println("Bağlantı Başarısız");
        }



    }



    public ArrayList<kullanicilar> oyunculariGetir(){
        try {
            ArrayList<kullanicilar> cikti = new ArrayList<kullanicilar>();

            statement = con.createStatement();
            String sorgu = "Select * From oyuncular";
            ResultSet rs = statement.executeQuery(sorgu);

            while(rs.next()){
                String kullanici_adi = rs.getString("kullaniciAdi");
                int skor = rs.getInt("skor");

                cikti.add(new kullanicilar(kullanici_adi,skor));

            }
            return cikti;


        } catch (SQLException ex) {
            Logger.getLogger(OyunKayitEkrani.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }

    }


    /**
     * Creates new form OyunKayitEkrani
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        k_adi_girisi = new javax.swing.JTextField();
        cikti_mesaj = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 250));

        jButton1.setText("Başla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ana Ekrana Dön");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        k_adi_girisi.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        k_adi_girisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_adi_girisiActionPerformed(evt);
            }
        });

        cikti_mesaj.setText("Kullanıcı adınızı giriş yapınız");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(67, 67, 67)
                                                .addComponent(k_adi_girisi, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(103, 103, 103)
                                                .addComponent(cikti_mesaj)))
                                .addContainerGap(97, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(cikti_mesaj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(k_adi_girisi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton2)
                                        .addComponent(jButton1))
                                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        setVisible(false);
        Oyun_Ana_menu oyunMenu = new Oyun_Ana_menu();
        oyunMenu.setVisible(true);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        if(k_adi_girisi.getText().isBlank()){
            cikti_mesaj.setText("Geçersiz Kullanıcı Adı Tekrar Deneyin...");
        }
        else{
            kullaniciEkle();
            setVisible(false);
            new OyunEkrani().oyunuCalistir();
        }
    }

    private void k_adi_girisiActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    Oyun oyun = new Oyun();
    public void kullaniciEkle(){

        String sorgu = "Insert Into oyuncular (kullaniciAdi,skor) VALUES (?,?)";
        try {
            preparedStatement = con.prepareStatement(sorgu);
            preparedStatement.setString(1,k_adi_girisi.getText());
            preparedStatement.setString(2, String.valueOf(oyun.getOyunSkoru()));
            preparedStatement.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(OyunKayitEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }


    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OyunKayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OyunKayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OyunKayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OyunKayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OyunKayitEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel cikti_mesaj;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField k_adi_girisi;
    // End of variables declaration
}
